# Generated by Django 4.0.3 on 2022-05-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='chinese',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='score',
            name='english',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='score',
            name='math',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='score',
            name='nature',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='score',
            name='sname',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
